version: '2.1'
services:
  web:
      build: haproxy
      ports:
          - "0.0.0.0:80:80"
      links:
          - app1:backend01
          - app2:backend02
  app1:
      build: tomcat

  app2:
      build: tomcat

  etcd:
      build: etcd
      volumes:
          - ./local/etcd:/var/lib/etcd/etcd-cluster.etcd

  postgresql1:
      build: postgresql
      environment:
          - STKEEPER_PG_LISTEN_ADDRESS postgresql1
          - STKEEPER_LISTEN_ADDRESS postgresql1
      volumes:
          - ./local/keeper1:/keeper
      links:
          - etcd:etcd

  postgresql2:
      build: postgresql
      environment:
          - STKEEPER_PG_LISTEN_ADDRESS postgresql2
          - STKEEPER_LISTEN_ADDRESS postgresql2
      volumes:
          - ./local/keeper2:/keeper
      links:
          - etcd:etcd
          - postgresql1:postgresql1
            
  sentinel:
      build: stolon-sentinel
      links:
          - etcd:etcd

  stolon-proxy:
      build: stolon-proxy
      ports:
          - "127.0.0.1:5432:5432"
      links:
          - etcd:etcd
