version: '2.1'
services:
  web:
      build: haproxy
      ports:
          - "0.0.0.0:80:80"
      links:
          - app1:backend01
          - app2:backend02
  app1:
      build: tomcat
      volumes:
          - /opt/wabapps1:/usr/local/tomcat/webapps

  app2:
      build: tomcat
      volumes:
          - /opt/wabapps2:/usr/local/tomcat/webapps

  etcd:
      build: etcd
      volumes:
          - ./local/etcd:/var/lib/etcd/etcd-cluster.etcd

  postgresql1:
      build: postgresql
      ports:
          - "15432:5432"
      environment:
          - STKEEPER_PG_LISTEN_ADDRESS postgresql1
          - STKEEPER_LISTEN_ADDRESS postgresql1
      volumes:
          - ./local/keeper1:/keeper
      links:
          - etcd:etcd

  postgresql2:
      build: postgresql
      ports:
          - "25432:5432"
      environment:
          - STKEEPER_PG_LISTEN_ADDRESS postgresql2
          - STKEEPER_LISTEN_ADDRESS postgresql2
      volumes:
          - ./local/keeper2:/keeper
      links:
          - etcd:etcd
          - postgresql1:postgresql1
            
  sentinel:
      build: stolon-sentinel
      links:
          - etcd:etcd

  stolon-proxy:
      build: stolon-proxy
      ports:
          - "127.0.0.1:5432:5432"
      links:
          - etcd:etcd
